version: '3.8'

services:
  web:
    build: .
    image: emilykbrown/coffeeshop:latest
    container_name: apache_php
    ports:
      - "8082:80"  # Changed from 8080 to 8082 to avoid port conflicts
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"  # Maps phpMyAdmin to port 8081
