version: '3.8'

services:
  coffeeapp:
    build: .
    container_name: coffeeapp
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: coffeeapp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: coffeeapp_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: coffeeapp-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: phpmyadmin
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
